{{- if .Values.route.enabled }}
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: lab-runner
  labels:
    app.kubernetes.io/name: lab-runner
    app.kubernetes.io/instance: lab-runner
spec:
  to:
    kind: Service
    name: lab-runner
    weight: 100
  port:
    targetPort: 8080
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
{{- end }}
