---
apiVersion: v1
kind: Service
metadata:
  name: lab-runner
  labels:
    app.kubernetes.io/name: lab-runner
    app.kubernetes.io/instance: lab-runner
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
  selector:
    app.kubernetes.io/name: lab-runner
    app.kubernetes.io/instance: lab-runner
